'use client';

import { useEffect, useMemo, useState } from 'react';
import { Plus, Pencil, Trash2, X } from 'lucide-react';
import { campaignRepository } from '../repositories/campaign-repository';
import { campaignDaySchema, campaignSchema, congregationSchema, pointSchema, timeBlockSchema } from '../schemas/campaign-schemas';
import type { Campaign, CampaignCongregation, CampaignDay, Congregation, Point, TimeBlock } from '../domain/types';

const statusLabels: Record<Campaign['status'], string> = { draft: 'Borrador', registration_open: 'Inscripciones abiertas', planning: 'Planificación', published: 'Publicado', active: 'En curso', completed: 'Finalizada' };
const emptyCampaign = { name: '', description: '', locationName: '', locationDetails: '', defaultCapacityPerBlock: '', maxPointsDefault: '', status: 'draft' };

function ErrorText({ error }: { error?: string }) { return error ? <p className="mt-2 text-sm text-red-700">{error}</p> : null; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold text-slate-700"><span className="mb-1.5 block">{label}</span>{children}</label>; }
const inputClass = 'h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-base text-slate-900 focus:outline-none focus:ring-2 focus:ring-teal-700';
const buttonClass = 'inline-flex min-h-11 items-center justify-center gap-2 rounded-xl px-4 text-sm font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-teal-700 focus:ring-offset-2';

export function CampaignAdmin() {
  const [campaigns, setCampaigns] = useState<Campaign[]>([]); const [selected, setSelected] = useState<Campaign | null>(null); const [creating, setCreating] = useState(false); const [error, setError] = useState('');
  useEffect(() => campaignRepository.subscribeCampaigns(setCampaigns), []);
  useEffect(() => { if (selected) setSelected(campaigns.find((item) => item.id === selected.id) || null); }, [campaigns, selected?.id]);
  async function create(formData: FormData) { const values = Object.fromEntries(formData); const parsed = campaignSchema.safeParse(values); if (!parsed.success) return setError(parsed.error.issues[0].message); try { const id = await campaignRepository.createCampaign(parsed.data); setSelected({ id, ...parsed.data }); setCreating(false); setError(''); } catch { setError('No se pudo crear la campaña. Revisa tu conexión e inténtalo nuevamente.'); } }
  if (selected) return <CampaignEditor campaign={selected} onBack={() => setSelected(null)} />;
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-semibold text-teal-700">Configuración</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Campañas</h1><p className="mt-2 text-slate-600">Crea y prepara campañas antes de abrir inscripciones.</p></div><button onClick={() => { setCreating(true); setError(''); }} className={`${buttonClass} bg-teal-700 text-white hover:bg-teal-800`}><Plus className="h-5 w-5" />Nueva campaña</button></div>
    {creating && <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-bold">Nueva campaña</h2><p className="mt-1 text-sm text-slate-600">Comienza como borrador; podrás completar días, bloques y puntos después.</p></div><button aria-label="Cerrar" onClick={() => setCreating(false)}><X /></button></div><CampaignForm initial={emptyCampaign} submitLabel="Crear campaña" onSubmit={create} error={error} /></section>}
    {campaigns.length === 0 && !creating ? <section className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="text-xl font-bold">Aún no hay campañas</h2><p className="mt-2 text-slate-600">Crea una campaña para comenzar su configuración.</p></section> : <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{campaigns.map((campaign) => <button key={campaign.id} onClick={() => setSelected(campaign)} className="rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:border-teal-700"><span className="inline-flex rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700">{statusLabels[campaign.status]}</span><h2 className="mt-4 text-xl font-bold text-slate-900">{campaign.name}</h2><p className="mt-2 min-h-10 text-sm text-slate-600">{campaign.locationName || 'Ubicación por definir'}</p><span className="mt-4 inline-block text-sm font-semibold text-teal-700">Configurar campaña →</span></button>)}</section>}
  </div>;
}

function CampaignForm({ initial, submitLabel, onSubmit, error }: { initial: Record<string, string>; submitLabel: string; onSubmit: (formData: FormData) => void | Promise<void>; error?: string }) { return <form action={onSubmit} className="grid gap-4 md:grid-cols-2"><div className="md:col-span-2"><Field label="Nombre"><input required name="name" defaultValue={initial.name} className={inputClass} /></Field></div><Field label="Ubicación general"><input name="locationName" defaultValue={initial.locationName} className={inputClass} /></Field><Field label="Capacidad objetivo por bloque"><input name="defaultCapacityPerBlock" type="number" min="0" defaultValue={initial.defaultCapacityPerBlock} className={inputClass} /></Field><Field label="Máximo de puntos"><input name="maxPointsDefault" type="number" min="0" defaultValue={initial.maxPointsDefault} className={inputClass} /></Field><Field label="Estado"><select name="status" defaultValue={initial.status} className={inputClass}>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><div className="md:col-span-2"><Field label="Descripción"><textarea name="description" defaultValue={initial.description} className={`${inputClass} h-24 py-2`} /></Field></div><div className="md:col-span-2"><Field label="Detalles de ubicación"><textarea name="locationDetails" defaultValue={initial.locationDetails} className={`${inputClass} h-20 py-2`} /></Field></div><div className="md:col-span-2"><ErrorText error={error} /><button className={`${buttonClass} mt-2 bg-teal-700 text-white hover:bg-teal-800`}>{submitLabel}</button></div></form>; }

function CampaignEditor({ campaign, onBack }: { campaign: Campaign; onBack: () => void }) {
  const [days, setDays] = useState<CampaignDay[]>([]); const [blocks, setBlocks] = useState<TimeBlock[]>([]); const [congregations, setCongregations] = useState<Congregation[]>([]); const [links, setLinks] = useState<CampaignCongregation[]>([]); const [points, setPoints] = useState<Point[]>([]); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { const stops = [campaignRepository.subscribeDays(campaign.id, setDays), campaignRepository.subscribeBlocks(campaign.id, setBlocks), campaignRepository.subscribeCongregations(setCongregations), campaignRepository.subscribeCampaignCongregations(campaign.id, setLinks), campaignRepository.subscribePoints(campaign.id, setPoints)]; return () => stops.forEach((stop) => stop()); }, [campaign.id]);
  const linkedIds = useMemo(() => new Set(links.map((link) => link.congregationId)), [links]);
  async function run(action: () => Promise<unknown>) { try { await action(); setError(''); setMessage('Cambios guardados.'); } catch (e) { setMessage(''); setError(e instanceof Error ? e.message : 'No se pudo guardar el cambio.'); } }
  const initial = { name: campaign.name, description: campaign.description || '', locationName: campaign.locationName || '', locationDetails: campaign.locationDetails || '', defaultCapacityPerBlock: campaign.defaultCapacityPerBlock?.toString() || '', maxPointsDefault: campaign.maxPointsDefault?.toString() || '', status: campaign.status };
  return <div className="space-y-8"><button onClick={onBack} className="text-sm font-semibold text-teal-700">← Volver a campañas</button><header><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">{statusLabels[campaign.status]}</span><h1 className="mt-3 text-3xl font-bold text-slate-900">{campaign.name}</h1><p className="mt-2 text-slate-600">Configura la información base sin necesidad de definir puntos todavía.</p></header><ErrorText error={error} />{message && <p className="rounded-xl bg-emerald-50 p-3 text-sm font-medium text-emerald-800">{message}</p>}
    <Section title="Información general"><CampaignForm initial={initial} submitLabel="Guardar información" error={error} onSubmit={(formData) => { const parsed = campaignSchema.safeParse(Object.fromEntries(formData)); if (!parsed.success) return setError(parsed.error.issues[0].message); return run(() => campaignRepository.updateCampaign(campaign.id, parsed.data)); }} /></Section>
    <Section title="Fechas y bloques" description="Cada día puede tener sus propios bloques horarios."><form action={(form) => { const parsed = campaignDaySchema.safeParse(Object.fromEntries(form)); if (!parsed.success) return setError(parsed.error.issues[0].message); return run(() => campaignRepository.saveDay(campaign.id, parsed.data)); }} className="flex flex-wrap gap-3"><input required name="date" type="date" className={inputClass} /><input name="label" placeholder="Etiqueta opcional" className={inputClass} /><button className={`${buttonClass} bg-teal-700 text-white`}><Plus className="h-4 w-4" />Agregar día</button></form>{days.map((day) => <div key={day.id} className="mt-5 rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold">{day.label || day.date}</h3><p className="text-sm text-slate-600">{day.date} · {day.active ? 'Activo' : 'Inactivo'}</p></div><button onClick={() => window.confirm('¿Eliminar este día?') && run(() => campaignRepository.deleteDay(day.id))} className={`${buttonClass} border border-red-200 text-red-700`}><Trash2 className="h-4 w-4" />Eliminar</button></div><div className="mt-4 space-y-2">{blocks.filter((block) => block.campaignDayId === day.id).map((block) => <div key={block.id} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm"><span>{block.startTime}–{block.endTime}{block.label ? ` · ${block.label}` : ''}</span><button onClick={() => window.confirm('¿Eliminar este bloque?') && run(() => campaignRepository.deleteBlock(block.id))} className="text-red-700"><Trash2 className="h-4 w-4" /></button></div>)}</div><form action={(form) => { const parsed = timeBlockSchema.safeParse(Object.fromEntries(form)); if (!parsed.success) return setError(parsed.error.issues[0].message); return run(() => campaignRepository.saveBlock(campaign.id, day.id, parsed.data)); }} className="mt-4 grid gap-2 sm:grid-cols-4"><input name="startTime" type="time" required className={inputClass} /><input name="endTime" type="time" required className={inputClass} /><input name="label" placeholder="Etiqueta opcional" className={inputClass} /><button className={`${buttonClass} bg-slate-900 text-white`}>Agregar bloque</button></form></div>)}</Section>
    <Section title="Congregaciones participantes" description="Las congregaciones se administran por separado y pueden asociarse a una o más campañas."><form action={(form) => { const parsed = congregationSchema.safeParse(Object.fromEntries(form)); if (!parsed.success) return setError(parsed.error.issues[0].message); return run(() => campaignRepository.saveCongregation(parsed.data)); }} className="flex flex-wrap gap-3"><input name="name" required placeholder="Nueva congregación" className={inputClass} /><button className={`${buttonClass} bg-slate-900 text-white`}>Crear congregación</button></form><div className="mt-4 space-y-2">{congregations.map((item) => { const link = links.find((entry) => entry.congregationId === item.id); return <div key={item.id} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-3"><span>{item.name}</span>{link ? <button onClick={() => run(() => campaignRepository.removeCampaignCongregation(link.id))} className="text-sm font-semibold text-red-700">Quitar de campaña</button> : <button onClick={() => run(() => campaignRepository.addCampaignCongregation(campaign.id, item.id))} className="text-sm font-semibold text-teal-700">Asociar</button>}</div>; })}</div></Section>
    <Section title="Puntos" description="Los puntos son opcionales en esta etapa y pueden agregarse después."><form action={(form) => { const parsed = pointSchema.safeParse(Object.fromEntries(form)); if (!parsed.success) return setError(parsed.error.issues[0].message); return run(() => campaignRepository.savePoint(campaign.id, parsed.data)); }} className="grid gap-3 md:grid-cols-3"><input name="name" required placeholder="Nombre del punto" className={inputClass} /><input name="locationText" placeholder="Ubicación o referencia" className={inputClass} /><button className={`${buttonClass} bg-slate-900 text-white`}><Plus className="h-4 w-4" />Agregar punto</button></form>{points.length === 0 ? <p className="mt-4 text-sm text-slate-600">Aún no hay puntos definidos. Esto no bloquea la campaña.</p> : <div className="mt-4 space-y-2">{points.map((point) => <div key={point.id} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-3"><span>{point.name}{point.locationText ? ` · ${point.locationText}` : ''}</span><button onClick={() => window.confirm('¿Eliminar este punto?') && run(() => campaignRepository.deletePoint(point.id))} className="text-red-700"><Trash2 className="h-4 w-4" /></button></div>)}</div>}</Section>
  </div>;
}
function Section({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-slate-900">{title}</h2>{description && <p className="mt-1 text-sm text-slate-600">{description}</p>}<div className="mt-5">{children}</div></section>; }
